name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

      - name: Test with coverage
        run: bun run test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: lucas-labs/kypi
          files: ./coverage/clover.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
